export type SightingKind = "photo" | "trail-cam" | "window" | "roadside";
export type SightingCluster = "nashville-south" | "columbus-ga" | "florida-run";

export type Sighting = {
  id: string;
  place: string;
  city: string;
  state: string;
  lat: number;
  lng: number;
  date: string;
  time: string;
  kind: SightingKind;
  cluster?: SightingCluster;
  witness: string;
  fileNumber: string;
  summary: string;
  details: string;
  oddities: string[];
  image: string;
  imageCaption: string;
};

export const SIGHTINGS: Sighting[] = [
  {
    id: "franklin",
    place: "Backyard on Cottonwood Lane",
    city: "Franklin",
    state: "TN",
    lat: 35.9251,
    lng: -86.8689,
    date: "October 2, 2026",
    time: "2:14 AM",
    kind: "photo",
    cluster: "nashville-south",
    witness: "The Cottonwood Lane porch cam",
    fileNumber: "TN-114",
    summary: "He stood by the swing set like he was waiting for the next turn.",
    details:
      "A Franklin family left the porch light on for the dog. At 2:14 AM the camera caught a lanky black cat standing upright in the grass, wearing a hat taller than the maple. The dog refused to go outside for three days. In the morning a single red-and-white striped sock was folded on the trampoline, as if someone had been very polite about leaving.",
    oddities: [
      "Hat taller than the backyard maple",
      "One striped sock, folded, on the trampoline",
      "Dog still will not look at the swing set",
    ],
    image: "/sightings/hatcat-franklin.jpg",
    imageCaption: "Porch camera still. Franklin, Tennessee.",
  },
  {
    id: "nolensville",
    place: "Mill Creek Greenway bridge",
    city: "Nolensville",
    state: "TN",
    lat: 35.9523,
    lng: -86.6694,
    date: "September 28, 2026",
    time: "7:41 PM",
    kind: "photo",
    cluster: "nashville-south",
    witness: "A jogger who now only runs at noon",
    fileNumber: "TN-109",
    summary: "Tip-tap, tip-tap, on the wooden bridge. Then a bow. Then fog.",
    details:
      "A jogger on the Mill Creek Greenway heard careful footsteps on the footbridge — too slow for a person, too tall for a regular cat. Fog rolled in off the creek. At the far end of the path stood the Visitor, hat first. He bowed. The phone only kept the hat. The rest of him went thin, like steam.",
    oddities: [
      "Footsteps counted as 1-2, 1-2, then stopped",
      "Photo captured the hat and almost none of the cat",
      "Creek went silent for eleven minutes",
    ],
    image: "/sightings/hatcat-nolensville.jpg",
    imageCaption: "Greenway at dusk. Nolensville, Tennessee.",
  },
  {
    id: "thompsons",
    place: "Empty rec-field window",
    city: "Thompson's Station",
    state: "TN",
    lat: 35.802,
    lng: -86.9064,
    date: "October 4, 2026",
    time: "9:03 PM",
    kind: "window",
    cluster: "nashville-south",
    witness: "A kid doing homework by the back window",
    fileNumber: "TN-118",
    summary: "He was on the soccer field. He waved. Homework was not finished.",
    details:
      "From a dark kitchen window, the soccer field behind the houses looked empty except for the moon. Then the hat rose over the far goal. The Visitor stood in the center circle and waved with one paw, slow and friendly, the way a substitute teacher waves. When the lights on the field flickered, he was gone. The grass in the center circle was pressed flat in the shape of two very small shoes and one very large brim.",
    oddities: [
      "Wave described as 'too polite'",
      "Center circle flattened in a brim shape",
      "Homework still incomplete",
    ],
    image: "/sightings/hatcat-thompsons.jpg",
    imageCaption: "Through the glass. Thompson's Station, Tennessee.",
  },
  {
    id: "spring-hill",
    place: "Deer camera at the tree line",
    city: "Spring Hill",
    state: "TN",
    lat: 35.7512,
    lng: -86.93,
    date: "September 19, 2026",
    time: "3:33 AM",
    kind: "trail-cam",
    cluster: "nashville-south",
    witness: "Trail camera #7 (meant for deer)",
    fileNumber: "TN-101",
    summary: "The deer never came. Something else looked into the lens.",
    details:
      "A Spring Hill trail camera was set for bucks. At 3:33 AM it fired. Frame one: a lanky black cat in a towering striped hat, staring straight into the infrared like he knew the password. Frame two: empty yard. Frame three: the bird feeder full of black jellybeans. The homeowner dumped the jellybeans. By morning the feeder was full again.",
    oddities: [
      "Timestamp stuck on 3:33 for two extra frames",
      "Bird feeder refilled with black jellybeans",
      "No deer on the card for the rest of the week",
    ],
    image: "/sightings/hatcat-springhill.jpg",
    imageCaption: "Infrared trail camera. Spring Hill, Tennessee.",
  },
  {
    id: "columbia",
    place: "Late-night grocery lot",
    city: "Columbia",
    state: "TN",
    lat: 35.6151,
    lng: -87.0353,
    date: "October 1, 2026",
    time: "11:47 PM",
    kind: "photo",
    cluster: "nashville-south",
    witness: "Night-shift cart collector",
    fileNumber: "TN-112",
    summary: "He was waiting in the far lane like the store owed him a box.",
    details:
      "The last cart collector in Columbia locked the doors and saw him under the one flickering lamp: upright, hat scraping the dark, standing beside a lonely shopping cart. He did not move. He appeared to be waiting for something that was not on sale. When the collector blinked, the cart was still there. The cat was not. Inside the cart: six identical cans of tuna and a child's drawing of a very tall hat.",
    oddities: [
      "Six cans of tuna, no receipt",
      "Child's hat drawing in the cart",
      "Lamp still flickers only in that lane",
    ],
    image: "/sightings/hatcat-columbia.jpg",
    imageCaption: "Grocery lot, one lamp. Columbia, Tennessee.",
  },
  {
    id: "fairview",
    place: "Shoulder of Highway 100",
    city: "Fairview",
    state: "TN",
    lat: 35.9817,
    lng: -87.1214,
    date: "October 5, 2026",
    time: "10:22 PM",
    kind: "roadside",
    cluster: "nashville-south",
    witness: "A driver who slowed down and then wished they had not",
    fileNumber: "TN-121",
    summary: "Headlights caught the hat first. The rest of him was already watching.",
    details:
      "West of Fairview, Highway 100 goes dark between the trees. A driver saw a stripe of red and white at the tree line and thought it was a surveying pole. It was not. The Visitor stood just off the asphalt, hat in the high beams, eyes like two dimes. He did not hitchhike. He did not run. He tipped the hat as the car passed. The radio, which had been playing a basketball game, played a music-box song for exactly eight seconds, then returned to the score.",
    oddities: [
      "Radio played a music-box tune for 8 seconds",
      "No corresponding pole in daylight",
      "Hat-tip confirmed by passenger",
    ],
    image: "/sightings/hatcat-fairview.jpg",
    imageCaption: "Highway 100 at night. Fairview, Tennessee.",
  },
  {
    id: "columbus-ga-trampoline",
    place: "Backyard on Bradley Drive",
    city: "Columbus",
    state: "GA",
    lat: 32.448,
    lng: -84.94,
    date: "October 7, 2026",
    time: "8:16 PM",
    kind: "photo",
    cluster: "columbus-ga",
    witness: "A ten-year-old who was supposed to be in bed",
    fileNumber: "GA-041",
    summary: "He did not knock. He bounced. The hat stayed on.",
    details:
      "Columbus, Georgia, after dinner. A backyard camera was still recording because the dog had barked at nothing. Frame one: empty trampoline. Frame two: the Visitor on the mat, upright, hat taller than the safety net. Frame three: mid-air — all four paws tucked, brim perfectly level, like a gymnast who had been doing this for centuries. Frame four: the mat still wobbling, nobody there, except one red-and-white striped sock folded on the spring pad as if he had taken turns politely. The kid at the window counted seven bounces. The counter on the camera says eleven.",
    oddities: [
      "Seven bounces counted, camera says eleven",
      "Hat did not wobble in mid-air",
      "Striped sock left on the mat, folded",
      "Dog barked at nothing for twenty minutes after",
    ],
    image: "/sightings/hatcat-columbus-ga-trampoline.jpg",
    imageCaption: "Backyard camera still. Columbus, Georgia.",
  },
  {
    id: "phenix-trampoline",
    place: "Riverwalk fence, 13th Street",
    city: "Phenix City",
    state: "AL",
    lat: 32.4715,
    lng: -85.012,
    date: "October 7, 2026",
    time: "9:02 PM",
    kind: "window",
    cluster: "columbus-ga",
    witness: "An apartment window and whoever was brushing teeth",
    fileNumber: "AL-197",
    summary: "He tested the bounce from the Alabama side. Georgia never noticed.",
    details:
      "From a second-story bathroom window, the Chattahoochee looked like spilled ink. In the lit yard across the way — technically still Georgia, emotionally still a trampoline — the Visitor stood with one long paw on the frame, pressing down once, twice, the way you test a diving board before you commit. He looked up at the window. He did not wave. He bounced once, low and courteous, and the hat did not tip. When the toothbrush paused, he was gone. In the morning the trampoline springs were warm and the safety net had a perfect cat-shaped hole that repaired itself by lunch.",
    oddities: [
      "Springs still warm at dawn",
      "Net hole shaped like a cat, self-repaired",
      "Only one bounce, described as 'very polite'",
    ],
    image: "/sightings/hatcat-phenix-trampoline.jpg",
    imageCaption: "Through the glass. Phenix City, Alabama.",
  },
  {
    id: "columbus-park",
    place: "Flat Rock Park play field",
    city: "Columbus",
    state: "GA",
    lat: 32.522,
    lng: -84.878,
    date: "October 7, 2026",
    time: "6:47 PM",
    kind: "photo",
    cluster: "columbus-ga",
    witness: "A coach locking the gate who now locks it twice",
    fileNumber: "GA-044",
    summary: "He bowed to the trampoline and left chalk that counted itself.",
    details:
      "Flat Rock Park after the last soccer practice. The coach turned off the field lights and saw him by the little trampoline pad near the playground — upright, hat scraping the dusk, bowing the way a substitute teacher bows when the bell was wrong but he was trying anyway. The Visitor touched the mat once with two paws, nodded, and walked toward the tree line on his hind legs. Chalk appeared on the sidewalk: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, then a little drawing of a hat. The coach did not have chalk in his bag. The trampoline pad had a single deep bounce dent, like something heavy and happy had visited.",
    oddities: [
      "Chalk count to twenty plus hat drawing",
      "Coach had no chalk",
      "One deep bounce dent remained until rain",
    ],
    image: "/sightings/hatcat-columbus-park.jpg",
    imageCaption: "Play field at dusk. Columbus, Georgia.",
  },
  {
    id: "midland-revere",
    place: "Corner of Revere Street",
    city: "Midland",
    state: "GA",
    lat: 32.5934,
    lng: -84.8262,
    date: "October 9, 2026",
    time: "10:31 PM",
    kind: "photo",
    cluster: "columbus-ga",
    witness: "A porch light that was not supposed to be on",
    fileNumber: "GA-051",
    summary: "He stood in the only circle of light on the block, like the corner had saved him a seat.",
    details:
      "Midland after the crickets had taken over. Revere Street bends where the lots get wooded and the mailboxes sit back in pine needles. One streetlight — orange, humming — paints the curb and nothing else. Under it, exactly on the corner, the Visitor waited upright in that striped hat, paws at his sides, facing the dark yards as if he were listening for a trampoline he could not find yet. A neighbor's camera caught three seconds: hat, eyes, then the light flickered once and he was between the trees, still walking on two legs. In the morning the corner had no tracks on the asphalt, only one warm spot on the sidewalk where the light pool had been, and every dog on the block refused the side yard.",
    oddities: [
      "Only visible under the streetlight pool",
      "Light flickered once; then empty corner",
      "Warm spot on sidewalk with no sun",
      "Dogs refused side yards all day",
    ],
    image: "/sightings/hatcat-midland-revere.jpg",
    imageCaption: "Revere Street corner. Midland, Georgia.",
  },
  {
    id: "ardmore",
    place: "Alabama Welcome Center, I-65",
    city: "Ardmore",
    state: "AL",
    lat: 34.992,
    lng: -86.8445,
    date: "October 8, 2026",
    time: "6:41 AM",
    kind: "photo",
    cluster: "florida-run",
    witness: "A family that only stopped to photograph the sign",
    fileNumber: "AL-201",
    summary: "He was already under Welcome to Alabama, as if he had been holding the state line.",
    details:
      "Dawn on I-65. The Welcome Center lights were still on. The Visitor stood beside the brick sign in that impossible hat, waiting like a greeter who had not been hired. A minivan pulled in for the usual border photo. In every frame the family later printed, he is in the background, perfectly still, smiling too much. The brochure rack had been restocked overnight with a single pamphlet: What To Do When the Water Comes. Nobody remembers stocking it.",
    oddities: [
      "Border photo has an extra tall figure in every print",
      "Only one pamphlet left in the rack",
      "Greeter swore she had already said good morning to him",
    ],
    image: "/sightings/hatcat-ardmore.jpg",
    imageCaption: "Welcome Center at dawn. Ardmore, Alabama.",
  },
  {
    id: "birmingham",
    place: "Shoulder of I-65, downtown",
    city: "Birmingham",
    state: "AL",
    lat: 33.5207,
    lng: -86.8025,
    date: "October 8, 2026",
    time: "8:12 AM",
    kind: "roadside",
    cluster: "florida-run",
    witness: "A trucker who radioed it in and then unsay the radio",
    fileNumber: "AL-208",
    summary: "He walked the white line toward Florida like the speed limit was a suggestion.",
    details:
      "Morning traffic stacked under the overpasses. On the shoulder, facing the wrong way if you believe in cars, the Visitor walked south with the hat in the skyline. Trucks honked. He tipped the brim without breaking stride. A DOT camera kept three seconds. Frame one: the cat. Frame two: the hat. Frame three: only the painted line, still wet, as if something very polite had just passed.",
    oddities: [
      "Walking against traffic, never hit",
      "DOT clip is three frames and then snow",
      "Shoulder paint was wet with no rain",
    ],
    image: "/sightings/hatcat-birmingham.jpg",
    imageCaption: "I-65 shoulder. Birmingham, Alabama.",
  },
  {
    id: "calera",
    place: "Giant beaver travel center, I-65",
    city: "Calera",
    state: "AL",
    lat: 33.1096,
    lng: -86.7539,
    date: "October 8, 2026",
    time: "9:04 AM",
    kind: "photo",
    cluster: "florida-run",
    witness: "A cashier who does not remember taking the jerky",
    fileNumber: "AL-214",
    summary: "He posed with the beaver. The beaver did not ask to be posed with.",
    details:
      "The busiest bathroom in Alabama. Fluorescent noon at 9 AM. The Visitor stood in the parking lot beside the giant beaver, holding a bag of jerky as if it were a diplomatic gift. He did not get in line. He did not blink in the photos. By the time the next car parked, the beaver statue was wearing a tiny red-and-white paper hat that would not stay on in the wind and also would not come off. The cashier found a damp sand dollar in the till.",
    oddities: [
      "Beaver statue acquired a paper hat",
      "Sand dollar in the register",
      "Jerky bag empty, receipt printed 00:00",
    ],
    image: "/sightings/hatcat-calera.jpg",
    imageCaption: "Travel-center lot. Calera, Alabama.",
  },
  {
    id: "dothan",
    place: "The big peanut in the park",
    city: "Dothan",
    state: "AL",
    lat: 31.2232,
    lng: -85.3905,
    date: "October 8, 2026",
    time: "12:18 PM",
    kind: "photo",
    cluster: "florida-run",
    witness: "A kid with boiled peanuts who is still waiting for a thank-you",
    fileNumber: "AL-221",
    summary: "He inspected the giant peanut. The peanut did not pass.",
    details:
      "Last real stop before the panhandle. Humid noon. The Visitor stood at the peanut monument and tapped it once, like a man checking a melon. A kid offered him a boiled peanut from a paper bag. He accepted with both hands, very grave, and did not eat it. At dusk the same peanut was found on top of a streetlight, steaming, which boiled peanuts should not do at dusk. The monument had a new hairline crack in the shape of a brim.",
    oddities: [
      "Boiled peanut later found on a streetlight",
      "Hairline crack shaped like a hat brim",
      "Kid says he bowed before taking it",
    ],
    image: "/sightings/hatcat-dothan.jpg",
    imageCaption: "Peanut monument. Dothan, Alabama.",
  },
  {
    id: "panama-city",
    place: "Hathaway Bridge walkway",
    city: "Panama City",
    state: "FL",
    lat: 30.1872,
    lng: -85.73,
    date: "October 8, 2026",
    time: "3:03 PM",
    kind: "photo",
    cluster: "florida-run",
    witness: "A driver who slowed down and caused a polite backup",
    fileNumber: "FL-301",
    summary: "He checked the wind over the bay. The flags all agreed with him.",
    details:
      "The bridge to the beach towns was already swaying in a weather that had not been named yet. Mid-span, on the pedestrian rail, the Visitor stood with one long claw up, testing the air the way a cook tests an oven. Condo towers in the distance. Water the wrong green. Cars slowed. Someone filmed it and swore it was a mascot. Then every flag on the bridge pointed inland at the same second, and he was already walking west, toward 30A, hat first.",
    oddities: [
      "All bridge flags pointed inland at once",
      "Bay water described as 'the wrong green'",
      "Phone video skips the moment he leaves",
    ],
    image: "/sightings/hatcat-panama-city.jpg",
    imageCaption: "Hathaway Bridge. Panama City, Florida.",
  },
  {
    id: "inlet-beach",
    place: "Dune line, public beach access",
    city: "Inlet Beach",
    state: "FL",
    lat: 30.2756,
    lng: -86.0015,
    date: "October 8, 2026",
    time: "5:55 PM",
    kind: "photo",
    cluster: "florida-run",
    witness: "A couple who thought it was a costume until the gulf went flat",
    fileNumber: "FL-308",
    summary: "He planted a cardboard sign in the sand: Hurricane is coming.",
    details:
      "End of the drive. Inlet Beach, 30A, the gulf the color of old nickels. The Visitor stood at the dune line in that tall striped hat and held a weathered cardboard sign in both claws. The letters were careful, almost courteous: Hurricane is coming. People on the access path laughed, then stopped laughing, because the water went flat as a table. He set the sign in the sand, tipped the hat toward the houses, and walked toward the surf without leaving footprints below the high-tide line. The sign was still there at dark. The letters had not smudged. Overnight the wind found them anyway.",
    oddities: [
      "Sign text: Hurricane is coming",
      "Gulf went flat for eleven minutes",
      "No footprints below the tide line",
    ],
    image: "/sightings/hatcat-inlet-beach.jpg",
    imageCaption: "Dune line at dusk. Inlet Beach, Florida.",
  },
  {
    id: "salem",
    place: "Woods off Witch Hill Road",
    city: "Salem",
    state: "MA",
    lat: 42.5195,
    lng: -70.8967,
    date: "October 31, 2025",
    time: "11:59 PM",
    kind: "photo",
    witness: "Tour-group straggler with a cheap flashlight",
    fileNumber: "MA-088",
    summary: "Salem has plenty of costumes. This one did not come off.",
    details:
      "A late walking tour lost one guest at the edge of the trees. The guest found the trees first. Between the trunks: a black cat standing like a butler, hat scraping fog. He did not say boo. He held still until the flashlight died, then the flashlight came back on, and the path was empty except for a little paper hat, perfectly folded, sitting on a stump.",
    oddities: [
      "Flashlight died and revived on its own",
      "Origami hat left on a stump",
      "Tour guide now counts guests twice",
    ],
    image: "/sightings/hatcat-salem.jpg",
    imageCaption: "Tree line after the tour. Salem, Massachusetts.",
  },
  {
    id: "new-orleans",
    place: "Gas-lamp alley off Royal",
    city: "New Orleans",
    state: "LA",
    lat: 29.9584,
    lng: -90.0644,
    date: "August 12, 2026",
    time: "1:12 AM",
    kind: "photo",
    witness: "A saxophone case and whoever was carrying it",
    fileNumber: "LA-044",
    summary: "He tipped his hat in the steam and the alley applauded itself.",
    details:
      "Rain turned a Quarter alley into a mirror. At the far end, under a sick gas lamp, the Visitor stood in the steam and tipped that impossible hat. A musician swore the bricks clapped, just once, like a polite audience. No one else was there. The next morning the lamp wouldn't light until someone said 'thank you' out loud, which the musician did, because New Orleans teaches you manners.",
    oddities: [
      "Bricks 'clapped' once",
      "Lamp refused to light until thanked",
      "Puddle reflected the hat after he was gone",
    ],
    image: "/sightings/hatcat-nola.jpg",
    imageCaption: "Wet alley, French Quarter. New Orleans, Louisiana.",
  },
  {
    id: "flagstaff",
    place: "Desert rest stop, northbound",
    city: "Flagstaff",
    state: "AZ",
    lat: 35.1983,
    lng: -111.6513,
    date: "July 4, 2026",
    time: "12:01 AM",
    kind: "photo",
    witness: "A family that only stopped for the vending machine",
    fileNumber: "AZ-017",
    summary: "He was beside the picnic table. The chips were already gone.",
    details:
      "A rest stop east of Flagstaff at midnight: one vending machine, one picnic table, a lot of quiet. The Visitor stood by the table in that tall striped hat as if he had been assigned the night shift. The family did not get out. They locked the doors and watched. He looked at the vending machine. The machine dropped a bag of chips with nobody paying. By the time they circled the lot, only the empty bag remained, folded into a tiny hat.",
    oddities: [
      "Vending machine vend with no coins",
      "Chip bag folded into a hat",
      "Picnic table frost in July",
    ],
    image: "/sightings/hatcat-flagstaff.jpg",
    imageCaption: "Rest stop after midnight. Flagstaff, Arizona.",
  },
  {
    id: "hoh",
    place: "Moss trail, Hoh Rain Forest",
    city: "Forks",
    state: "WA",
    lat: 47.8609,
    lng: -123.9346,
    date: "June 21, 2026",
    time: "4:44 AM",
    kind: "photo",
    witness: "A ranger who does not spook easily",
    fileNumber: "WA-009",
    summary: "The hat stuck up through the fog like a striped periscope.",
    details:
      "On the summer solstice a ranger walking the mossy loop saw the hat first — a red-and-white stack poking through fog above a fallen log. Then the yellow-green eyes. The Visitor stood as if the forest had grown him overnight. Birds did not sing. When the ranger blinked, the log was only a log. On it: wet pawprints in a straight, careful line, and one stripe of red mud that would not wash off in the rain.",
    oddities: [
      "Birds silent for the whole loop",
      "Straight-line pawprints on the log",
      "Red mud stripe that rain would not lift",
    ],
    image: "/sightings/hatcat-rainforest.jpg",
    imageCaption: "Moss and fog. Hoh Rain Forest, Washington.",
  },
  {
    id: "chicago",
    place: "Brick alley off Milwaukee",
    city: "Chicago",
    state: "IL",
    lat: 41.9103,
    lng: -87.6773,
    date: "January 9, 2026",
    time: "8:08 PM",
    kind: "photo",
    witness: "Third-floor apartment, fire-escape view",
    fileNumber: "IL-061",
    summary: "He was in the alley looking up, like he had the wrong window.",
    details:
      "Sodium streetlight. Dumpsters. A fire escape. From a third-floor kitchen someone looked down and saw the Visitor in the alley, hat taller than the first landing, staring up as if he had an appointment. He did not climb. He waited. Then he looked at the next window over, decided that was not it either, and walked around the corner on two legs. The building cats yowled in a chord that nobody has been able to hum since.",
    oddities: [
      "Looked at two windows, then left",
      "Building cats yowled in one chord",
      "Snow in the alley melted only under the brim",
    ],
    image: "/sightings/hatcat-chicago.jpg",
    imageCaption: "Alley, looking up. Chicago, Illinois.",
  },
  {
    id: "key-west",
    place: "End of an empty pier",
    city: "Key West",
    state: "FL",
    lat: 24.5551,
    lng: -81.78,
    date: "May 3, 2026",
    time: "2:00 AM",
    kind: "photo",
    witness: "Night fisherman who caught nothing after",
    fileNumber: "FL-033",
    summary: "He stood at the end of the dock like the ocean had invited him.",
    details:
      "The pier was empty except for a lanky black cat at the last plank, hat against the moon, looking at the water as if something down there owed him a story. The fisherman did not call out. The Visitor turned, put one paw to the brim, and the tide made a little clap. After that the fish stopped biting until sunrise. A pelican sat where he had stood and would not move until someone said, quietly, 'excuse me.'",
    oddities: [
      "Tide clapped once",
      "No fish until sunrise",
      "Pelican held the spot like a usher",
    ],
    image: "/sightings/hatcat-keys.jpg",
    imageCaption: "Empty pier. Key West, Florida.",
  },
];

export const PORTRAIT_SRC = "/sightings/hatcat-portrait.jpg";

export function getSighting(id: string): Sighting | undefined {
  return SIGHTINGS.find((s) => s.id === id);
}

export const TENNESSEE_CLUSTER = SIGHTINGS.filter((s) => s.cluster === "nashville-south");
export const COLUMBUS_GA_CLUSTER = SIGHTINGS.filter((s) => s.cluster === "columbus-ga");
export const FLORIDA_RUN = SIGHTINGS.filter((s) => s.cluster === "florida-run");

export const US_CENTER: [number, number] = [39.5, -96.5];
export const US_ZOOM = 4;
export const TENNESSEE_CENTER: [number, number] = [35.82, -86.88];
export const TENNESSEE_ZOOM = 9;
export const COLUMBUS_GA_CENTER: [number, number] = [32.48, -84.92];
export const COLUMBUS_GA_ZOOM = 10;
export const FLORIDA_RUN_CENTER: [number, number] = [32.55, -86.15];
export const FLORIDA_RUN_ZOOM = 6;
export const YOU_ARE_HERE_ZOOM = 12;

export const DRIVE_PATH: [number, number][] = [
  [35.9251, -86.82],
  [35.7512, -86.83],
  [35.5, -86.87],
  [32.448, -84.94],
  [32.5934, -84.8262],
  [32.4715, -85.012],
  [34.992, -86.8445],
  [33.5207, -86.8025],
  [33.1096, -86.7539],
  [32.3668, -86.2999],
  [31.8088, -85.97],
  [31.2232, -85.3905],
  [30.1872, -85.73],
  [30.2756, -86.0015],
];
